import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

export interface StatementRow {
  date: string;
  type: string;
  asset: string;
  amount: string;
  fee: string;
  status: string;
  reference: string;
}

const styles = StyleSheet.create({
  page: { padding: 32, fontSize: 9, fontFamily: "Helvetica" },
  brand: { fontSize: 8, letterSpacing: 2, textTransform: "uppercase", color: "#B8892E", marginBottom: 2 },
  title: { fontSize: 16, marginBottom: 4, fontFamily: "Helvetica-Bold" },
  meta: { fontSize: 9, color: "#555", marginBottom: 16 },
  table: { display: "flex", width: "100%" },
  headerRow: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#333",
    paddingBottom: 4,
    marginBottom: 4,
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#ddd",
    paddingVertical: 3,
  },
  headerCell: { fontFamily: "Helvetica-Bold", fontSize: 8 },
  cell: { fontSize: 8 },
  colDate: { width: "16%" },
  colType: { width: "14%" },
  colAsset: { width: "10%" },
  colAmount: { width: "16%", textAlign: "right" },
  colFee: { width: "12%", textAlign: "right" },
  colStatus: { width: "12%" },
  colRef: { width: "20%" },
  footer: { marginTop: 24, fontSize: 7, color: "#888" },
});

export function StatementDocument({
  clientName,
  clientEmail,
  from,
  to,
  rows,
}: {
  clientName: string;
  clientEmail: string;
  from: string;
  to: string;
  rows: StatementRow[];
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>XWallet Asia — Private Wealth &amp; Digital Asset Custody</Text>
        <Text style={styles.title}>Account Statement</Text>
        <Text style={styles.meta}>
          {clientName} ({clientEmail}) · {from} to {to}
        </Text>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={[styles.headerCell, styles.colDate]}>Date</Text>
            <Text style={[styles.headerCell, styles.colType]}>Type</Text>
            <Text style={[styles.headerCell, styles.colAsset]}>Asset</Text>
            <Text style={[styles.headerCell, styles.colAmount]}>Amount</Text>
            <Text style={[styles.headerCell, styles.colFee]}>Fee</Text>
            <Text style={[styles.headerCell, styles.colStatus]}>Status</Text>
            <Text style={[styles.headerCell, styles.colRef]}>Reference</Text>
          </View>
          {rows.map((r, i) => (
            <View key={i} style={styles.row} wrap={false}>
              <Text style={[styles.cell, styles.colDate]}>{r.date}</Text>
              <Text style={[styles.cell, styles.colType]}>{r.type}</Text>
              <Text style={[styles.cell, styles.colAsset]}>{r.asset}</Text>
              <Text style={[styles.cell, styles.colAmount]}>{r.amount}</Text>
              <Text style={[styles.cell, styles.colFee]}>{r.fee}</Text>
              <Text style={[styles.cell, styles.colStatus]}>{r.status}</Text>
              <Text style={[styles.cell, styles.colRef]}>{r.reference}</Text>
            </View>
          ))}
          {rows.length === 0 && <Text style={styles.cell}>No transactions in this period.</Text>}
        </View>

        <Text style={styles.footer}>
          Generated by XWallet Asia. This statement reflects platform ledger records only and is not a
          substitute for on-chain verification.
        </Text>
      </Page>
    </Document>
  );
}
